### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by unclecheese** [unclecheese/next-poc#1]
* [ ] Refactor TemplateManifest to rely more on remote state, (SSR pages will need this).
* [ ] Cache graphql build resolvers by BUILD_ID
* [ ] Deprecate `pageQuery`, `batchQuery` in favour of naming convention based `src/**/*.graphql` files
* [ ] Static payload builder API (backend)
* [ ] Elemental component code gen for `prebuild`
* [ ] Pluggable `prebuild`
* [ ] Shortcode parsing (GraphQL default args PR)
* [ ] Navigation helper component
